# Generated by Django 2.0.4 on 2018-04-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('ua', models.CharField(blank=True, max_length=30)),
                ('referer', models.URLField()),
                ('path', models.URLField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('ip', 'path')},
        ),
    ]
