# Generated by Django 2.0.4 on 2018-04-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ip',
            field=models.CharField(max_length=45),
        ),
    ]
