# Generated by Django 2.0.4 on 2018-04-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20180424_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ua',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
