# Generated by Django 2.0.4 on 2018-05-05 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_auto_20180424_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
