# Generated by Django 2.0.4 on 2018-06-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0004_visitor_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
