# Generated by Django 2.0.4 on 2018-06-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0006_auto_20180614_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
