# Generated by Django 2.0.4 on 2018-06-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0007_auto_20180614_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
