# Generated by Django 2.0.4 on 2018-06-18 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_project_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='icon',
        ),
    ]
