# Generated by Django 2.0.4 on 2018-04-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='head',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
