# Generated by Django 2.0.4 on 2018-04-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180424_1655'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='post_id',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
