# Generated by Django 2.0.4 on 2018-06-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='temperature',
            field=models.CharField(max_length=10),
        ),
    ]
