# Generated by Django 2.0.4 on 2018-06-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0002_auto_20180614_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='og',
            new_name='sg',
        ),
    ]
