# Generated by Django 2.0.4 on 2018-06-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0004_log_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='yeast',
            field=models.CharField(default='Lalvin EC-1118', max_length=50),
            preserve_default=False,
        ),
    ]
