# Generated by Django 2.0.4 on 2018-06-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0005_log_yeast'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
