# Generated by Django 2.0.4 on 2018-09-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0006_log_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='log',
        ),
        migrations.RemoveField(
            model_name='log',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='log',
            name='preprocess',
        ),
        migrations.AddField(
            model_name='log',
            name='label',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='log',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
